# Nama Pipeline
name: Mini CI/CD Pipeline - PyTest

# Trigger: Kapan pipeline ini harus dijalankan
on:
  push:
    branches: [ main ] # Jalankan saat ada push ke branch 'main'
  pull_request:
    branches: [ main ] # Juga jalankan saat ada Pull Request ke 'main'

# Langkah-langkah (Jobs) yang akan dieksekusi
jobs:
  test_and_report:
    # Menggunakan runner Ubuntu terbaru
    runs-on: ubuntu-latest

    # Variabel Lingkungan (Opsional, untuk keamanan)
    env:
      API_ENDPOINT: https://jsonplaceholder.typicode.com

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4
      
    - name: 2. Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Menggunakan versi Python terbaru
        
    - name: 3. Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html # Instal plugin untuk laporan HTML
        
    - name: 4. Run Automated Tests with PyTest
      # Perintah untuk menjalankan pengujian dan menghasilkan laporan
      run: |
        pytest --junitxml=test-results.xml --html=test-report.html --self-contained-html

    - name: 5. Upload Test Report (Artefak)
      # Langkah ini menyimpan laporan agar dapat diunduh setelah pipeline selesai
      uses: actions/upload-artifact@v4
      if: always() # Selalu jalankan langkah ini, bahkan jika pengujian gagal
      with:
        name: PyTest-Test-Report
        path: test-report.html
